---
  ## Modified from github.com/gantsign/ansible-role-oh-my-zsh
- name: install dependencies
  become: yes
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - zsh

- name: clone oh-my-zsh for users
  tags:
    # Suppress warning: [ANSIBLE0006] git used in place of git module
    # Git module doesn't allow us to set `core.autocrlf=input`.
    - skip_ansible_lint
  become: yes
  become_user: 'vagrant'
  # core.autocrlf=input prevents https://github.com/robbyrussell/oh-my-zsh/issues/4402
  command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh'
  args:
    chdir: '~/'
    creates: '~/.oh-my-zsh'

- name: set permissions of oh-my-zsh for users
  become: yes
  file:
    path: '~/.oh-my-zsh'
    # Prevent the cloned repository from having insecure permissions. Failing to do
    # so causes compinit() calls to fail with "command not found: compdef" errors
    # for users with insecure umasks (e.g., "002", allowing group writability).
    mode: 'go-w'
    recurse: yes

- name: set default shell for users
  become: yes
  user:
    name: 'vagrant'
    shell: /bin/zsh

- name: write .zshrc for users
  become: yes
  become_user: 'vagrant'
  template:
    src: zshrc.j2
    dest: '~/.zshrc'
    backup: yes
    mode: 'u=rw,go=r'